// export const ActionTypes = {
//     SET_STATE_LOGIN: "SET_STATE_LOGIN",
//     SET_STATE_USER: "SET_STATE_USER",
//     SET_STATE_PAGING: "SET_STATE_PAGING",
//     SET_CATEGORY_ID: "SET_CATEGORY_ID",
//     SET_CATEGORY: "SET_CATEGORY",
//     SET_CATEGORY_LIST: "SET_CATEGORY_LIST",

// }
export const SET_STATE_LOGIN = 'SET_STATE_LOGIN';
export type SET_STATE_LOGIN = typeof SET_STATE_LOGIN;

export const SET_STATE_USER =  'SET_STATE_USER';
export type SET_STATE_USER = typeof SET_STATE_USER;

export const SET_STATE_PAGING =  'SET_STATE_PAGING';
export type SET_STATE_PAGING = typeof SET_STATE_PAGING;

export const SET_CATEGORY_ID =  'SET_CATEGORY_ID';
export type SET_CATEGORY_ID = typeof SET_CATEGORY_ID;

export const SET_CATEGORY =  'SET_CATEGORY';
export type SET_CATEGORY = typeof SET_CATEGORY;

export const SET_CATEGORY_LIST =  'SET_CATEGORY_LIST';
export type SET_CATEGORY_LIST = typeof SET_CATEGORY_LIST;